Project_CarSystem/LUT_CarSystem/Models/Car.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace LUT_CarSystem.Models
{
    public class Car
    {
        
       
        public string Type { get; set; }
        public string CarName { get; set; }
        [Key]
        public int CarId { get; set; }
        public double Money { get; set; }
        //未出租0，已出租1，维修中2
        [RegularExpression(@"^0$|^1$|^2$")]
        public int State { get; set; }

        //public string getState(int value)
        //{
        //    return value == 0 ? "空闲中" : value == 1 ? "租赁中" : "维修中";
        //}
        public string[] StringState = { "空闲中", "租赁中", "维修中" };
    }
}

Project_CarSystem/LUT_CarSystem/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LUT_CarSystem.DAL;
using LUT_CarSystem.Models;
using PagedList;

namespace LUT_CarSystem.Controllers
{
    public class CarsController : Controller
    {
        private CarContext db = new CarContext();

        // GET: Cars
        
        public ActionResult Index(string sortCar, string currentFilter, string SearchString, int? page,string CarName)
        {
            ViewBag.currentFilter = sortCar;
            if (SearchString != null)
            {
                page = 1;
            }
            else
            {
                SearchString = currentFilter;
            }

            ViewBag.CurrentFilter = SearchString;

            ViewBag.TypeSortParm = String.IsNullOrEmpty(sortCar) ? "type_desc" : "";
            ViewBag.MoneySortParm = sortCar == "Money" ? "money_desc" : "Money";
            ViewBag.StateSortParm = sortCar == "State" ? "state_desc" : "State";
            var cars = from s in db.Car select s;

            var TypeLst = new List<string>();
            string value = SearchString;
            var TypeQry = from d in db.Car
                          select d.Type;
            TypeLst.AddRange(TypeQry.Distinct());
            if (!string.IsNullOrEmpty(SearchString))
            {
                cars = cars.Where(s => s.Type == value);
            }
            if (!string.IsNullOrEmpty(CarName))
            {
                cars = cars.Where(s => s.CarName == CarName);
            }

            switch (sortCar)
            {
                case "type_desc":
                    cars = cars.OrderByDescending(s => s.Type);
                    break;
                case "Money":
                    cars = cars.OrderBy(s => s.Money);
                    break;
                case "money_desc":
                    cars = cars.OrderByDescending(s => s.Money);
                    break;
                case "State":
                    cars = cars.OrderBy(s => s.State);
                    break;
                case "state_desc":
                    cars = cars.OrderByDescending(s => s.State);
                    break;
                default:
                    cars = cars.OrderBy(s => s.Type);
                    break;
            }
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            return View(cars.ToPagedList(pageNumber, pageSize));
        }

        // GET: Cars/Details/5
        [FunctionFilter(0)]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Car.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        // GET: Cars/Create
        [FunctionFilter(2)]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cars/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        [FunctionFilter(2)]
        public ActionResult Create([Bind(Include = "CarId,Type,CarName,Money,State")] Car car)
        {
            if (ModelState.IsValid)
            {
                db.Car.Add(car);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(car);
        }

        // GET: Cars/Edit/5
        [FunctionFilter(2)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Car.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        // POST: Cars/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        [FunctionFilter(2)]
        public ActionResult Edit([Bind(Include = "CarId,Type,CarName,Money,State")] Car car)
        {
            if (ModelState.IsValid)
            {
                db.Entry(car).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(car);
        }

        // GET: Cars/Delete/5
        [FunctionFilter(2)]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Car.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        // POST: Cars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [FunctionFilter(2)]
        public ActionResult DeleteConfirmed(int id)
        {
            Car car = db.Car.Find(id);
            db.Car.Remove(car);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet, ActionName("Rent")]
        [FunctionFilter(2)]
        public ActionResult Rent(int id)
        {
            Car car = db.Car.Find(id);
            if (car.State == 0)
            {
                car.State = 1;
                db.Entry(car).State = EntityState.Modified;
                db.SaveChanges();
                ViewBag.Message = "成功租赁了" + car.CarName;
            }
            else if (car.State == 1)
            {
                ViewBag.Message = car.CarName + "已经被租赁了，请挑选其它车辆";
            }
            else
            {
                ViewBag.Message = car.CarName + "正在维修中";
            }
            //return View(car);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

Project_CarSystem/LUT_CarSystem/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LUT_CarSystem.DAL;
using LUT_CarSystem.Models;
using PagedList;

namespace LUT_CarSystem.Controllers
{

   
    public class OrdersController : Controller
    {
        private CarContext db = new CarContext();

        // GET: Orders
        public ActionResult Index(string sortOrder, string currentFilter, string SearchString, int? page)
        {
            ViewBag.currentFilter = sortOrder;
            if (SearchString != null)
            {
                page = 1;
            }
            else
            {
                SearchString = currentFilter;
            }

            ViewBag.CurrentFilter = SearchString;

            ViewBag.StartTimeSortParm = String.IsNullOrEmpty(sortOrder) ? "StartTime" : "";
            ViewBag.TotalRentSortParm = sortOrder == "TotalRent" ? "totalRent_desc" : "TotalRent";
            ViewBag.EndTimeSortParm = sortOrder == "EndTime" ? "endTime_desc" : "EndTime";
            ViewBag.SalesmanNameSortParm = sortOrder == "SalesmanName" ? "salesmanName_desc" : "SalesmanName";
            var orders = from s in db.Order select s;

            var DriverIdLst = new List<long>();
            long value = Convert.ToInt64(SearchString);
            var DriverIdQry = from d in db.Order
                              orderby d.DriverId
                              select d.DriverId;
            DriverIdLst.AddRange(DriverIdQry.Distinct());
            if (!string.IsNullOrEmpty(SearchString))
            {
                orders = orders.Where(s => s.DriverId == value);
            }

            switch (sortOrder)
            {
                case "StartTime":
                    orders = orders.OrderBy(s => s.StartTime);
                    break;
                case "totalRent_desc":
                    orders = orders.OrderByDescending(s => s.TotalRent);
                    break;
                case "TotalRent":
                    orders = orders.OrderBy(s => s.TotalRent);
                    break;
                case "endTime_desc":
                    orders = orders.OrderByDescending(s => s.EndTime);
                    break;
                case "EndTime":
                    orders = orders.OrderBy(s => s.EndTime);
                    break;
                case "salesmanName_desc":
                    orders = orders.OrderByDescending(s => s.SalesmanName);
                    break;
                case "SalesmanName":
                    orders = orders.OrderBy(s => s.SalesmanName);
                    break;
                default:
                    orders = orders.OrderByDescending(s => s.StartTime);
                    break;
            }

            int pageSize = 6;
            int pageNumber = (page ?? 1);
            return View(orders.ToPagedList(pageNumber, pageSize));
        }


        // GET: Orders/Details/5
        [FunctionFilter(0)]
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Order.Find(id);
            
            if (order == null)
            {
                return View("ErrorHttpNotFound");
            }
            return View(order);
        }
        // GET: Orders/Create
        [FunctionFilter(0)]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Orders/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        [FunctionFilter(0)]
        public ActionResult Create([Bind(Include = "OrderId,DriverId,CarId,TotalRent,StartTime,EndTime,SalesmanName")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Order.Add(order);
                db.SaveChanges();
                /*  改变车辆的租赁状态  */
                Car car = db.Car.Find(order.CarId);
                if (car.State == 0)
                {
                    car.State = 1;
                    db.Entry(car).State = EntityState.Modified;
                    db.SaveChanges();
                    ViewBag.Message = "成功租赁了" + car.CarName;
                }
                else if (car.State == 1)
                {
                    ViewBag.Message = car.CarName + "已经被租赁了，请挑选其它车辆";
                }
                else
                {
                    ViewBag.Message = car.CarName + "正在维修中";
                }

                return RedirectToAction("Index");
            }

            return View(order);
        }

        // GET: Orders/Edit/5
        [FunctionFilter(2)]
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Order.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        [FunctionFilter(2)]
        public ActionResult Edit([Bind(Include = "OrderId,DriverId,CarId,TotalRent,StartTime,EndTime,SalesmanName")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(order);
        }

        // GET: Orders/Delete/5
        [FunctionFilter(2)]
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Order.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [FunctionFilter(2)]
        public ActionResult DeleteConfirmed(long id)
        {
            Order order = db.Order.Find(id);
            db.Order.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project_CarSystem/LUT_CarSystem/Views/Cars/Create.cshtml
@model LUT_CarSystem.Models.Car

@{
    ViewBag.Title = "Create";
}

<h2>添加车辆</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Car Add</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @*@Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="control-label col-md-2"><b>车种</b></div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @*@Html.LabelFor(model => model.CarName, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="control-label col-md-2"><b>车辆名</b></div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.CarName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CarName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @*@Html.LabelFor(model => model.CarName, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="control-label col-md-2"><b>车辆牌号</b></div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.CarId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CarId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @*@Html.LabelFor(model => model.Money, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="control-label col-md-2"><b>日租金</b></div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Money, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Money, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @*@Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="control-label col-md-2"><b>租赁状态</b></div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="添加" class="btn btn-default" />
        </div>
    </div>
</div>
}

Project_CarSystem/LUT_CarSystem/Views/Cars/Delete.cshtml
@model LUT_CarSystem.Models.Car

@{
    ViewBag.Title = "Delete";
}

<h2>车辆信息删除</h2>

<h3>你确定要删除该车辆的信息吗?</h3>
<div>
    <h4>Car Infomation Delete</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @*@Html.DisplayNameFor(model => model.Type)*@
            车种
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.CarName)*@
            车辆名
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarName)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.Money)*@
            日租金
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Money)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.State)*@
            租赁状态
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StringState[model.State])
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="删除" class="btn btn-default" /> |
            @Html.ActionLink("返回列表", "Index", new { }, htmlAttributes: new { @class = "btn btn-info" })
        </div>
    }
</div>

Project_CarSystem/LUT_CarSystem/Views/Cars/Details.cshtml
@model LUT_CarSystem.Models.Car

@{
    ViewBag.Title = "Details";
}

<h2>车辆详情</h2>

<div>
    <h4>Car Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @*@Html.DisplayNameFor(model => model.Type)*@
            车种
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.CarName)*@
            车辆名
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarName)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.CarName)*@
            车编号
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarId)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.Money)*@
            日租金
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Money)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.State)*@
            租赁状态
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("编辑", "Edit", new { id = Model.CarId },htmlAttributes: new { @class = "btn btn-info" }) 
    @Html.ActionLink("返回列表", "Index", new { }, htmlAttributes: new { @class = "btn btn-success" })
</p>

Project_CarSystem/LUT_CarSystem/Views/Cars/Edit.cshtml
@model LUT_CarSystem.Models.Car

@{
    ViewBag.Title = "Edit";
}

<h2>车辆信息编辑</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Car Infomation Edit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CarId)
        @*@Html.HiddenFor(model => model.StringState)*@

        <div class="form-group">
            @*@Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="control-label col-md-2"><b>车种</b></div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.CarName, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="control-label col-md-2"><b>车辆名</b></div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.CarName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CarName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.Money, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="control-label col-md-2"><b>日租金</b></div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Money, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Money, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="control-label col-md-2"><b>租赁状态</b></div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="保存" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("返回列表", "Index", new { },htmlAttributes: new { @class = "btn btn-info" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project_CarSystem/LUT_CarSystem/Views/Cars/Index.cshtml
@model PagedList.IPagedList<LUT_CarSystem.Models.Car>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
}

<h2>车辆信息</h2>

<p>
    @Html.ActionLink("添加车辆", "Create", new { }, htmlAttributes: new { @class = "btn btn-info" })
</p>

<p>
    @using (Html.BeginForm("Index", "Cars", FormMethod.Get))
    {
    <p>
        车种搜索: @Html.TextBox("SearchString")
        <input type="submit" value="查询" class="btn btn-success" />
        <b style="color:red">@ViewBag.Message</b>
    </p>
}
    </p>

    <table class="table">
        <tr>
            <!--<th>-->
            @*@Html.DisplayNameFor(model => model.Type)*@
            <!--车种
    </th>
    <th>-->
            @*@Html.DisplayNameFor(model => model.CarName)*@
            <!--车辆名
    </th>
    <th>-->
            @*@Html.DisplayNameFor(model => model.Money)*@
            <!--日租金
    </th>
    <th>-->
            @*@Html.DisplayNameFor(model => model.State)*@
            <!--租赁状态
    </th>-->
            <th>
                @Html.ActionLink("车种", "Index", new { sortCar = ViewBag.TypeSortParm })
            </th>
            <th>
                车辆名
            </th>
            <th>
                车辆编号
            </th>
            <th>
                @Html.ActionLink("日租金", "Index", new { sortCar = ViewBag.MoneySortParm })
            </th>
            <th>
                @Html.ActionLink("租赁状态", "Index", new { sortCar = ViewBag.StateSortParm })
            </th>
            <th>
                <div align="center">
                    操作
                </div>
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Type)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CarName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CarId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Money)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StringState[item.State])
            @*@Html.DisplayFor(modelItem => item.State)*@
        </td>
        <td>
            <div align="center">
                @Html.ActionLink("编辑", "Edit", new { id = item.CarId }, htmlAttributes: new { @class = "btn btn-info" })
                @Html.ActionLink("详情", "Details", new { id = item.CarId }, htmlAttributes: new { @class = "btn btn-default" })
                @Html.ActionLink("删除", "Delete", new { id = item.CarId }, htmlAttributes: new { @class = "btn btn-danger" })
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-success" data-toggle="modal" data-target="#@item.CarId " }>
                    租赁
                </button>
                <!-- Modal -->
                <div class="modal fade" id=@item.CarId tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title" id="myModalLabel">确定租赁</h4>
                            </div>
                            <div class="modal-body">
                                <div class="alert-success">
                                    车种：@Html.DisplayFor(modelItem => item.Type) <br />
                                    车辆名：@Html.DisplayFor(modelItem => item.CarName) <br />
                                    日租金：@Html.DisplayFor(modelItem => item.Money) <br />
                                    租赁状态：@Html.DisplayFor(modelItem => item.StringState[item.State]) <br />
                                    @*@Html.DisplayFor(modelItem => item.State) <br />*@
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                                @*@Html.ActionLink("确定", "Rent", "Cars", new { id = item.CarId }, htmlAttributes: new { @class = "btn btn-primary" })*@
                                @*<button type="button" class="btn btn-primary">确定</button>*@
                                @Html.ActionLink("确定", "Create", "Orders", new { id = item.CarId }, htmlAttributes: new { @class = "btn btn-primary" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </td>
    </tr>
        }

    </table>

    <br />
    当前页 @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) - 共 @Model.PageCount 页

    @Html.PagedListPager(Model, page => Url.Action("Index",
        new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))