Project_CarSystem/LUT_CarSystem/Models/Driver.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace LUT_CarSystem.Models
{
    public class Driver
    {
       
        [Key]
        public long DriverId { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        [RegularExpression(@"^男$|^女$")]
        public string Gender { get; set; }
        [RegularExpression(@"^(13[0-9]|14[01456879]|15[0-35-9]|16[2567]|17[0-8]|18[0-9]|19[0-35-9])\d{8}$")]
        public long Phone { get; set; }
        [RegularExpression(@"^\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$")]
        public string Email { get; set; }
        [RegularExpression(@"^.+省.+市.*$")]
        public string Address { get; set; }
        //普通用户0，管理员1，老板2
        public int Power { get; set; }


        public string[] StringPower = { "普通用户", "管理员", "公司高层" };
    }
}

Project_CarSystem/LUT_CarSystem/Controllers/DriversController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LUT_CarSystem.DAL;
using LUT_CarSystem.Models;
using PagedList;

namespace LUT_CarSystem.Controllers
{
    public class DriversController : Controller
    {
        private CarContext db = new CarContext();

        // GET: Drivers
        [FunctionFilter(2)]
        public ActionResult Index(string sortDriver, string currentFilter, string SearchString,int? page)
        {
            ViewBag.currentFilter = sortDriver;
            if (SearchString!=null)
            {
                page = 1;
            }
            else
            {
                SearchString = currentFilter;
            }

            ViewBag.CurrentFilter = SearchString;

            ViewBag.NameSortParm = String.IsNullOrEmpty(sortDriver) ? "Name" : "";
            ViewBag.GenderSortParm = sortDriver == "Gender" ? "gender_desc" : "Gender";
            ViewBag.AddressSortParm = sortDriver == "Address" ? "address_desc" : "Address";
            ViewBag.PowerSortParm = sortDriver == "Power" ? "power_desc" : "Power";
            var drivers = from s in db.Driver select s;

            var NameLst = new List<string>();
            var NameQry = from s in db.Driver select s.Name;
            NameLst.AddRange(NameQry.Distinct());
            if (!string.IsNullOrEmpty(SearchString))
            {
                drivers = drivers.Where(s => s.Name.Equals(SearchString));
            }

            switch (sortDriver)
            {
                case "Name":
                    drivers = drivers.OrderBy(s => s.Name);
                    break;
                case "gender_desc":
                    drivers = drivers.OrderByDescending(s => s.Gender);
                    break;
                case "Gender":
                    drivers = drivers.OrderBy(s => s.Gender);
                    break;
                case "address_desc":
                    drivers = drivers.OrderByDescending(s => s.Address);
                    break;
                case "Address":
                    drivers = drivers.OrderBy(s => s.Address);
                    break;
                case "power_desc":
                    drivers = drivers.OrderByDescending(s => s.Power);
                    break;
                case "Power":
                    drivers = drivers.OrderBy(s => s.Power);
                    break;
                default:
                    drivers = drivers.OrderByDescending(s => s.Name);
                    break;
            }
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            return View(drivers.ToPagedList(pageNumber,pageSize));
        }

        // GET: Drivers/Details/5
        [FunctionFilter(0)]
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Driver driver = db.Driver.Find(id);
            if (driver == null)
            {
                return HttpNotFound();
            }
            return View(driver);
        }

        // GET: Drivers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Drivers/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DriverId,Name,Password,Gender,Phone,Email,Address,Power")] Driver driver)
        {
            if (ModelState.IsValid)
            {
                db.Driver.Add(driver);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(driver);
        }

        // GET: Drivers/Edit/5
        [FunctionFilter(2)]
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Driver driver = db.Driver.Find(id);
            if (driver == null)
            {
                return HttpNotFound();
            }
            return View(driver);
        }

        // POST: Drivers/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        [FunctionFilter(2)]
        public ActionResult Edit([Bind(Include = "DriverId,Name,Password,Gender,Phone,Email,Address,Power")] Driver driver)
        {
            if (ModelState.IsValid)
            {
                db.Entry(driver).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(driver);
        }

        // GET: Drivers/Delete/5
        [FunctionFilter(2)]
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Driver driver = db.Driver.Find(id);
            if (driver == null)
            {
                return HttpNotFound();
            }
            return View(driver);
        }

        // POST: Drivers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [FunctionFilter(2)]
        public ActionResult DeleteConfirmed(long id)
        {
            Driver driver = db.Driver.Find(id);
            db.Driver.Remove(driver);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project_CarSystem/LUT_CarSystem/Views/Drivers/Create.cshtml
@model LUT_CarSystem.Models.Driver

@{
    ViewBag.Title = "Create";
}

<h2>用户信息创建</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Driver Infomation Add</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @*@Html.LabelFor(model => model.DriverId, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="control-label col-md-2">用户ID</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.DriverId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DriverId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @*@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="control-label col-md-2">用户名</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @*@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="control-label col-md-2">密码</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @*@Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="control-label col-md-2">性别</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @*@Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="control-label col-md-2">电话</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @*@Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="control-label col-md-2">邮箱</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @*@Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="control-label col-md-2">地址</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @*@Html.LabelFor(model => model.Power, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="control-label col-md-2">权限</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Power, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Power, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="新建" class="btn btn-default" />
        </div>
    </div>
</div>
}

Project_CarSystem/LUT_CarSystem/Views/Drivers/Delete.cshtml
@model LUT_CarSystem.Models.Driver

@{
    ViewBag.Title = "Delete";
}

<h2>用户信息删除</h2>

<h3>你确定要删除此用户的信息吗?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            用户名
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            密码
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            性别
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            电话
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            邮箱
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            地址
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            权限
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Power)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="删除" class="btn btn-default" /> |
            @Html.ActionLink("返回列表", "Index", new { }, htmlAttributes: new { @class = "btn btn-info" })
        </div>
    }
</div>

Project_CarSystem/LUT_CarSystem/Views/Drivers/Details.cshtml
@model LUT_CarSystem.Models.Driver

@{
    ViewBag.Title = "Details";
}

<h2>用户信息详情</h2>

<div>
    <h4>Driver Infomation Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            用户名
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            密码
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            性别
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            电话
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            邮箱
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            地址
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            权限
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Power)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("编辑", "Edit", new { id = Model.DriverId },htmlAttributes: new { @class = "btn btn-info" }) 
    @Html.ActionLink("返回列表", "Index", new { }, htmlAttributes: new { @class = "btn btn-success" })
</p>

Project_CarSystem/LUT_CarSystem/Views/Drivers/Edit.cshtml
@model LUT_CarSystem.Models.Driver

@{
    ViewBag.Title = "Edit";
}

<h2>用户信息编辑</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Driver Infomation Edit</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.DriverId)

    <div class="form-group">
        <div class="control-label col-md-2"><b>用户名</b></div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2"><b>密码</b></div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2"><b>性别</b></div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2"><b>电话</b></div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2"><b>邮箱</b></div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2"><b>地址</b></div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2"><b>权限</b></div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Power, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Power, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="保存" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("返回列表", "Index", new { }, htmlAttributes: new { @class = "btn btn-info" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project_CarSystem/LUT_CarSystem/Views/Drivers/Index.cshtml
@model PagedList.IPagedList<LUT_CarSystem.Models.Driver>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
}


<h2>租客信息</h2>

<p>
    @Html.ActionLink("新建用户", "Create", new { }, htmlAttributes: new { @class = "btn btn-info" })
</p>

<p>
    @using (Html.BeginForm("Index", "Drivers", FormMethod.Get))
    {
    <p>
        用户名搜索: @Html.TextBox("SearchString")
        <input type="submit" value="查询" class="btn btn-success" />
    </p>
}
    </p>

    <table class="table">
        <tr>
            <!--<th>-->
            @*@Html.DisplayNameFor(model => model.Name)*@
            <!--用户名
    </th>
    <th>-->
            @*@Html.DisplayNameFor(model => model.Gender)*@
            <!--性别
    </th>
    <th>-->
            @*@Html.DisplayNameFor(model => model.Phone)*@
            <!--电话
    </th>
    <th>-->
            @*@Html.DisplayNameFor(model => model.Email)*@
            <!--邮箱
    </th>
    <th>-->
            @*@Html.DisplayNameFor(model => model.Address)*@
            <!--地址
    </th>
    <th>-->
            @*@Html.DisplayNameFor(model => model.Power)*@
            <!--权限
    </th>-->

            <th>
                用户ID
            </th>
            <th>
                @Html.ActionLink("用户名", "Index", new { sortDriver = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                密码
            </th>
            <th>
                @Html.ActionLink("性别", "Index", new { sortDriver = ViewBag.GenderSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                电话
            </th>
            <th>
                邮箱
            </th>
            <th>
                @Html.ActionLink("地址", "Index", new { sortDriver = ViewBag.AddressSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("权限", "Index", new { sortDriver = ViewBag.PowerSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                操作
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DriverId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gender)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StringPower[item.Power])
        </td>
        <td>
            @Html.ActionLink("编辑", "Edit", new { id = item.DriverId }, htmlAttributes: new { @class = "btn btn-info" })
            @Html.ActionLink("详情", "Details", new { id = item.DriverId }, htmlAttributes: new { @class = "btn btn-default" })
            @Html.ActionLink("删除", "Delete", new { id = item.DriverId }, htmlAttributes: new { @class = "btn btn-danger" })
        </td>
    </tr>
        }

    </table>


    <br />
    当前页 @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) - 共 @Model.PageCount 页

    @Html.PagedListPager(Model, page => Url.Action("Index",
        new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))


   